### ISSUE TITLE
Hello, your work is very good. When can you publish the code

### ISSUE THREAD

**Issue by qppwddd** [LinWeizheDragon/Retrieval-Augmented-Visual-Question-Answering#1]

**Comment by LinWeizheDragon** [comment]
Hi,
Thanks for your interest. I was caught by COVID a few days ago and had to postpone the release plan. I will get to work on this soon and plan to release the code within the next month.

**Comment by LinWeizheDragon** [comment]
Hi, an initial version has been published. I am closing this issue.
