### ISSUE TITLE
vinvl_large

### ISSUE THREAD

**Issue by gsxf997** [LinWeizheDragon/Retrieval-Augmented-Visual-Question-Answering#10]
Hello, may I ask where I can download the "vinvl_large" model mentioned in Step 4: Running models?

**Comment by LinWeizheDragon** [comment]
Hi, I don't remember the details but it should come from this link:
https://github.com/microsoft/Oscar/blob/master/VinVL_MODEL_ZOO.md#image-captioning-on-coco
