### ISSUE TITLE
Could someone provide a trained checkpoint file

### ISSUE THREAD

**Issue by zhaoyongchao2019** [LinWeizheDragon/Retrieval-Augmented-Visual-Question-Answering#11]
![image](https://user-images.githubusercontent.com/50958273/232461472-19f6ec1e-58e4-45c4-9461-abf2b0df8d39.png)
If someone can help me, I would be extremely grateful.

**Comment by LinWeizheDragon** [comment]
Hello. I m travelling now. Can share when I return (in 2 days)

Best,
Weizhe Lin
________________________________
发件人: qiaoqiaoZhao ***@***.***>
发送时间: Monday, April 17, 2023 6:42:45 PM
收件人: LinWeizheDragon/Retrieval-Augmented-Visual-Question-Answering ***@***.***>
抄送: Subscribed ***@***.***>
主题: [LinWeizheDragon/Retrieval-Augmented-Visual-Question-Answering] Could someone provide a trained checkpoint file (Issue #11)


[image]<https://user-images.githubusercontent.com/50958273/232461472-19f6ec1e-58e4-45c4-9461-abf2b0df8d39.png>
If someone can help me, I would be extremely grateful.

―

**Comment by zhaoyongchao2019** [comment]
Thank you very much, and I wish you a pleasant journey.

**Comment by LinWeizheDragon** [comment]
Hi,

Unfortunately, I couldn't find the checkpoints that were generated using the updated codebase. The checkpoints generated when I sorted out the codebase were accidentally left in a remote machine that was closed at some point. But I think the following checkpoint should match the DPR checkpoint shared in the repository, even though its performance was reported to be ~53.7 VQA Score, which was slightly lower than the one you could get by running the codebase directly.

If you find it not matched or you really want to obtain higher performance, I'd suggest running the codebase on Google Colab, which is also a free space. Other platforms, such as AutoDL, also offer very cheap rent prices for A100/V100 (like 1.8 CNY/hour).

Link: https://pan.baidu.com/s/17Q_R1friv-XLEZWu4it28g?pwd=q4np 
passcode: q4np 

Best,
Weizhe Lin

**Comment by zhaoyongchao2019** [comment]
Forgive my poor English, I can only say thank you again to express my endless gratitude to you.

Best,
Yongchao Zhao

**Comment by 1286169349** [comment]
> Forgive my poor English, I can only say thank you again to express my endless gratitude to you.
> 
> Best, Yongchao Zhao

请问你能运行这个检查点文件吗？
下边是我运行的结果，请问你遇到了吗？
RuntimeError: Error(s) in loading state_dict for RagExecutor:
	size mismatch for model.generator.shared.weight: copying a param with shape torch.Size([32110, 1024]) from checkpoint, the shape in current model is torch.Size([30532, 1024]).
	size mismatch for model.generator.encoder.embed_tokens.weight: copying a param with shape torch.Size([32110, 1024]) from checkpoint, the shape in current model is torch.Size([30532, 1024]).
	size mismatch for model.generator.decoder.embed_tokens.weight: copying a param with shape torch.Size([32110, 1024]) from checkpoint, the shape in current model is torch.Size([30532, 1024]).
	size mismatch for model.generator.lm_head.weight: copying a param with shape torch.Size([32110, 1024]) from checkpoint, the shape in current model is torch.Size([30532, 1024]).
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
Best
jinlong
