### ISSUE TITLE
AttributeError: 'DPRQuestionEncoderTokenizerFast' object has no attribute 'resize_token_embeddings'

### ISSUE THREAD

**Issue by 1286169349** [LinWeizheDragon/Retrieval-Augmented-Visual-Question-Answering#13]
我只能使用本地加载的方式，加载了该分词器，为什么提示没有该属性呢

**Comment by 1286169349** [comment]
具体信息如下：
Traceback (most recent call last):
  File "/home/zzu_zxw/zjl_data/Retrieval-Augmented-Visual-Question-Answering/src/main.py", line 341, in <module>
    main(config)
  File "/home/zzu_zxw/zjl_data/Retrieval-Augmented-Visual-Question-Answering/src/main.py", line 153, in main
    executor = Train_Executor(config, data_loader_manager)#初始化Train_Executor，文件dpr_exexutor.py的41行
  File "/home/zzu_zxw/zjl_data/Retrieval-Augmented-Visual-Question-Answering/src/trainers/dpr_executor.py", line 53, in __init__
    self.model.resize_token_embeddings(len(self.tokenizer), len(self.decoder_tokenizer))
  File "/home/zzu_zxw/zjl_data/Retrieval-Augmented-Visual-Question-Answering/src/models/retriever/retriever_dpr.py", line 73, in resize_token_embeddings
    self.query_encoder.resize_token_embeddings(dim)
AttributeError: 'DPRQuestionEncoderTokenizerFast' object has no attribute 'resize_token_embeddings'

**Comment by LinWeizheDragon** [comment]
可能是因为你用的tokenizer是Fast版本
你试试看下面的这个设置
```local tokenizer_config = {
  "tokenizer": {
    "TokenizerClass": "DPRQuestionEncoderTokenizer",
    "TokenizerModelVersion": "facebook/dpr-question_encoder-single-nq-base",
    "SPECIAL_TOKENS":{
      "additional_special_tokens": ["<BOV>", "<SOV>", "<EOV>", "<BOQ>", "<EOQ>", "<BOC>", "<EOC>", "<BOK>", "<EOK>"],
    },
  },
  "decoder_tokenizer": {
    "TokenizerClass": "DPRContextEncoderTokenizer",
    "TokenizerModelVersion": "facebook/dpr-ctx_encoder-single-nq-base",
    "SPECIAL_TOKENS":{
      "additional_special_tokens": ["<BOV>", "<SOV>", "<EOV>", "<BOQ>", "<EOQ>", "<BOC>", "<EOC>", "<BOK>", "<EOK>"],
    },
  },
};
```

如果还是有问题，请尝试用一模一样的Huggingface transformers版本

**Comment by 1286169349** [comment]
我只能从本地加载模型，所以我从huggingface的https://huggingface.co/facebook/dpr-question_encoder-single-nq-base下载模型。但是加载之后为什么就是fast版本的呢？代码如下：
class DataLoaderWrapper():
    '''
    Data loader wrapper, general class definitions
    '''

    def __init__(self, config):
        self.config = config

        # Prepare for tokenizers
        # TokenizerClass = globals()[self.config.model_config.TokenizerClass]
        # self.tokenizer = TokenizerClass.from_pretrained(self.config.model_config.TokenizerModelVersion) #facebook/dpr-question_encoder-single-nq-base

        # 指定模型的本地路径
        model_path = "/home/zzu_zxw/zjl_data/Retrieval-Augmented-Visual-Question-Answering/src/models/facebook/dpr-question_encoder-single-nq-base"
        config_path = "/home/zzu_zxw/zjl_data/Retrieval-Augmented-Visual-Question-Answering/src/models/facebook/dpr-question_encoder-single-nq-base/config.json"
        vocab_path = "/home/zzu_zxw/zjl_data/Retrieval-Augmented-Visual-Question-Answering/src/models/facebook/dpr-question_encoder-single-nq-base/vocab.txt"
        self.tokenizer = AutoTokenizer.from_pretrained(model_path, config=config_path, vocab_file=vocab_path,trust_remote_code=True, local_files_only=True)

        self.SPECIAL_TOKENS = self.config.model_config.SPECIAL_TOKENS
        self.SPECIAL_TOKENS['additional_special_tokens'] = self.tokenizer.additional_special_tokens + self.SPECIAL_TOKENS['additional_special_tokens']
        
        self.tokenizer.add_special_tokens(self.SPECIAL_TOKENS)
        
        # Load second tokenizer if specified
        if self.config.model_config.get('DecoderTokenizerClass', None) is not None:
            # DecoderTokenizerClass = globals()[self.config.model_config.DecoderTokenizerClass]#'facebook/dpr-ctx_encoder-single-nq-base'
            # self.decoder_tokenizer = DecoderTokenizerClass.from_pretrained(self.config.model_config.DecoderTokenizerModelVersion)

            # 指定模型的本地路径
            model_path = "/home/zzu_zxw/zjl_data/Retrieval-Augmented-Visual-Question-Answering/src/models/facebook/dpr-ctx_encoder-single-nq-base"
            config_path = "/home/zzu_zxw/zjl_data/Retrieval-Augmented-Visual-Question-Answering/src/models/facebook/dpr-ctx_encoder-single-nq-base/config.json"
            vocab_path = "/home/zzu_zxw/zjl_data/Retrieval-Augmented-Visual-Question-Answering/src/models/facebook/dpr-ctx_encoder-single-nq-base/vocab.txt"
            self.decoder_tokenizer = AutoTokenizer.from_pretrained(model_path, config=config_path, vocab_file=vocab_path,trust_remote_code=True, local_files_only=True)

            self.DECODER_SPECIAL_TOKENS = self.config.model_config.DECODER_SPECIAL_TOKENS
            self.DECODER_SPECIAL_TOKENS['additional_special_tokens'] = self.decoder_tokenizer.additional_special_tokens + self.DECODER_SPECIAL_TOKENS['additional_special_tokens']
            self.decoder_tokenizer.add_special_tokens(self.DECODER_SPECIAL_TOKENS)
            
        else:
            self.decoder_tokenizer = self.tokenizer

        # Load feature extractor if specified
        if self.config.model_config.get('FeatureExtractorClass', None) is not None:
            # Load image feature extractor
            FeatureExtractorClass = globals()[self.config.model_config.FeatureExtractorClass]
            self.feature_extractor = FeatureExtractorClass.from_pretrained(self.config.model_config.FeatureExtractorModelVersion)
        else:
            self.feature_extractor = None

        # Prepare data for training
        # self.build_dataset()

**Comment by 1286169349** [comment]
我的transformers版本和您提供的一致

**Comment by LinWeizheDragon** [comment]
self.tokenizer = AutoTokenizer.from_pretrained
替换为
self.tokenizer = TokenizerClass.from_pretrained
试一下

**Comment by 1286169349** [comment]
谢谢你，解决了！哈哈哈，你人真好

**Comment by 1286169349** [comment]
还是存在错误：
AttributeError: 'DPRQuestionEncoderTokenizer' object has no attribute 'resize_token_embeddings'
我的transformers版本是4.12.5

**Comment by LinWeizheDragon** [comment]
我知道了  你这个是改出BUG了
tokenizer通过.add_special_tokens 增加新的special token
model 通过.resize_token_embeddings增加新的token embeddings
所以这里应该是用了tokenizer.resize_token_embeddings而不是self.model.resize_token_embeddings(len(self.tokenizer))

**Comment by LinWeizheDragon** [comment]
你需要仔细检查一下你修改的代码

**Comment by 1286169349** [comment]
谢谢，我明天继续看。我要回宿舍了，11点就要关门了！！！

**Comment by 1286169349** [comment]
谢谢，已经解决了，确实是模型加载错了，加载成tokenizer了
