### ISSUE TITLE
Model download problem

### ISSUE THREAD

**Issue by zhaoyongchao2019** [LinWeizheDragon/Retrieval-Augmented-Visual-Question-Answering#16]
Hello,I would like to use Oscar to generate captions. However, I am unable to access the link you provided, possibly due to Azure permissions issues. Unfortunately, it is currently not possible to obtain a free account on Azure in China. I would like to inquire if there are any other links available to download the pre-trained Oscar model. Alternatively, would it be possible for you to upload the model to a different cloud storage platform?

**Comment by LinWeizheDragon** [comment]
Hi, it seems that it is not a problem of yours. The official download link has expired.
I managed to upload the checkpoints (both VinVL and Oscar) here. I hope these will help your research.
https://drive.google.com/file/d/1nJ8iUy1juzk6pmYjXCWu9J0GtEnXKLDc/view?usp=sharing
https://drive.google.com/file/d/17l_pDo6t6SFlgLPL0UmHtYocaCfMlXXW/view?usp=sharing

**Comment by zhaoyongchao2019** [comment]
Thank you very much. Additionally, I also need the following files: oscar_dataset/coco_caption/[train/val/test].yaml. It seems that the links to these files are no longer valid. Can you please provide me with the new download links? I would greatly appreciate it.

**Comment by LinWeizheDragon** [comment]
Unfortunately, I did not keep these files either... I think I simply used their yaml files with minimum changes to paths.
https://github.com/microsoft/Oscar/issues/205#issuecomment-1703763202
Please check this post out. I tried the SAS token in this post but it does not work. If you successfully download the files, please let me know.

**Comment by EstrellaXyu** [comment]
> Thank you very much. Additionally, I also need the following files: oscar_dataset/coco_caption/[train/val/test].yaml. It seems that the links to these files are no longer valid. Can you please provide me with the new download links? I would greatly appreciate it.

Hello, we are also unable to download the .yaml file, have you successfully downloaded the file? can you please share it? Thanks a lot.

**Comment by LinWeizheDragon** [comment]
> > Thank you very much. Additionally, I also need the following files: oscar_dataset/coco_caption/[train/val/test].yaml. It seems that the links to these files are no longer valid. Can you please provide me with the new download links? I would greatly appreciate it.
> 
> Hello, we are also unable to download the .yaml file, have you successfully downloaded the file? can you please share it? Thanks a lot.

Unfortunately, I didn't keep those files on my side. Please contact the Oscar's authors for these files.... sad :(

**Comment by EstrellaXyu** [comment]
> > > Thank you very much. Additionally, I also need the following files: oscar_dataset/coco_caption/[train/val/test].yaml. It seems that the links to these files are no longer valid. Can you please provide me with the new download links? I would greatly appreciate it.
> > 
> > 
> > Hello, we are also unable to download the .yaml file, have you successfully downloaded the file? can you please share it? Thanks a lot.
> 
> Unfortunately, I didn't keep those files on my side. Please contact the Oscar's authors for these files.... sad :(

Thank you for your reply. Could you please explain how to modify lines 83-84 about the operation of "labels" in prepare_data_for_okvqa.py before running VinVL? Thanks a lot.
