### ISSUE TITLE
wandb connection problem

### ISSUE THREAD

**Issue by zhaoyongchao2019** [LinWeizheDragon/Retrieval-Augmented-Visual-Question-Answering#17]
Hello, last week I was able to run this program normally, but this week I don't know what went wrong. It keeps throwing an error and cannot access [api.wandb.ai](http://api.wandb.ai/). I want to try setting wandb to offline or simply not using wandb, but the information I found online couldn't solve my problem. I hope you can tell me which part of the code I should modify. Thank you very much.
![image](https://github.com/LinWeizheDragon/Retrieval-Augmented-Visual-Question-Answering/assets/50958273/cf5f04a1-0ad4-4110-bdec-9493676e4bff)

**Comment by LinWeizheDragon** [comment]
You can first try connecting to wandb with some toy codes to rule out the possibility of local network connection issues
And then you can set `WANDB_MODE` to `offline` to disable online logging.
https://docs.wandb.ai/guides/track/environment-variables

**Comment by zhaoyongchao2019** [comment]
Thank you, the error disappeared inexplicably today, and there is no problem now.

**Comment by zhaoyongchao2019** [comment]
你好，我又遇到这个问题了，我在main.py开头添加了os.environ["WANDB_MODE"] = "offline"，但依旧会报这个错误，请问是我添加的位置有错吗？如果你知道原因请告诉我

**Comment by LinWeizheDragon** [comment]
I did not encounter this problem recently. It may be that the connectivity in China is too unstable.  If you want to enforce offline mode, you can do by running `wandb offline` first under the working directory, and then run your experiments - there might be some codes that need to be altered to work with offline mode but it should be fine.
After you finish the experiment, you can do `wandb online` and then `wandb sync --sync-all` to upload these runs when the connection restores.
