### ISSUE TITLE
DPR problem

### ISSUE THREAD

**Issue by zhaoyongchao2019** [LinWeizheDragon/Retrieval-Augmented-Visual-Question-Answering#18]
Hello, I have a question about DPR that I would like to ask. For example, if I want to modify the input caption and target detection labels, how can I use these new inputs to modify the retrieved paragraphs from the article? I tried to find the answer in the code myself, but this part of the code is too complex and difficult to understand. Could you give me some hints?

**Comment by LinWeizheDragon** [comment]
Can you give an example? Not sure what "modify the paragraphs using new inputs" means.

**Comment by zhaoyongchao2019** [comment]
For example, now I have obtained the caption, object detection labels, and OCR text recognition. Then I input these three to DPR to obtain relevant external knowledge. However, if I switch the caption and object detection labels, will the external knowledge obtained by DPR change? Do I need to modify the function "LoadGoogleSearchPassageData", or will the retrieved knowledge automatically change with these three inputs being modified? By the way, may I ask if you are Chinese?

**Comment by LinWeizheDragon** [comment]
1. The external passages do not change since they come from the corpus directly. If you have a DPR trained on question+caption+objects, and then you switch off caption and objects, the retrieved documents may change (because the query embedding has changed since you have a shorter input now), but if doc A is retrieved in both cases, the content of doc A will not change. That basically says, previously you retrieve A B C D E, and now you may retrieve A B E F G due to the query change.
2. And it is recommended to retrain the DPR using only question inputs if you really want to switch off caption+objects, in most cases.
3. Yes.

**Comment by zhaoyongchao2019** [comment]
我用中文重新表述一下，就是我现在把caption和目标检测的标签换成新的，然后我只更改了他们相应的载入的函数，但是我觉得这样好像更改不了DPR的输出，如果我想达到这个目的，我应该修改代码的那个部分

**Comment by LinWeizheDragon** [comment]
所以你就是想更换caption和objects的标签来源？有几种办法
LoadVinVLFeatures 用来加载VinVL的object detection的结果  你可以把数据准备成和原来这里的输入一样的格式  那就可以直接被读取
LoadOscarCaptionFeatures 用来加载Oscar生成的captions  同理，你可以准备成一样的格式 然后直接更换config里面的路径到你的新标签数据
或者，你可以单独写一个LoadNewCaptionFeatures之类的  在config里面替换掉LoadOscarCaptionFeatures  这个函数  你就可以实现自己的读取代码
最后这些内容都会被LoadOKVQAData读取，保存到每一个question的数据当中，以便dataloader调用。例如
https://github.com/LinWeizheDragon/Retrieval-Augmented-Visual-Question-Answering/blob/155d6e66e322c6b86ac637a28a090c6803ac3d23/src/data_loader_manager/data_loader_okvqa.py#L210

https://github.com/LinWeizheDragon/Retrieval-Augmented-Visual-Question-Answering/blob/155d6e66e322c6b86ac637a28a090c6803ac3d23/src/data_loader_manager/data_loader_okvqa.py#L286

这里，就是读取`LoadOscarCaptionFeatures`当中准备好的caption数据，然后和OKVQA的数据合并起来。

**Comment by LinWeizheDragon** [comment]
顺便一提   注意删除cache  如果更改了这些内容的话
https://github.com/LinWeizheDragon/Retrieval-Augmented-Visual-Question-Answering/blob/155d6e66e322c6b86ac637a28a090c6803ac3d23/src/data_loader_manager/data_loader_okvqa.py#L262
不然每次都是读取的之前cache好的数据

**Comment by zhaoyongchao2019** [comment]
不是，我的意思是我现在更改了caption和目标检测的标签，做法跟你上面说的一样修改了LoadVinVLFeatures和LoadOscarCaptionFeatures函数，但我想搞清楚的是我只改变这两个函数去更新这两个输入的话我检索出来的知识会不会因此改变？如果不会那么我该如何修改代码？之所以这么问是因为我记得你的论文说过使用FAISS先把检索到的知识先进行处理方便后面的检索。

**Comment by LinWeizheDragon** [comment]
会改变，记得清空cache  然后确定你的新标签被`LoadOKVQAData`正确加载
DPR训练的时候，因为document encoder的参数发生改变，所以训练完之后都是需要重新编码，然后用FAISS进行indexing的，所以每个文档的embedding根据所用的DPR参数不同都会不一样。
跑test的时候是会重新跑indexing的流程的，如果你的DPR模型参数不变，那么所有文档生成的embedding也是不会变的。

你更换input，导致的是query embedding的变化，因为query embedding变了，所以就算文档的embedding没变，你获取到的documents必然也会发生变化。如果你用了更准确的caption和objects的识别结果，理论上retrieve出来的文档准确度会提升（例如Recall）。但是我们一般建议你用新的input重新训练DPR模型，让DPR模型更fit到你的新的input上，这样一般会有更好的retrieval performance

**Comment by zhaoyongchao2019** [comment]
非常感谢，完全明白了

**Comment by zhaoyongchao2019** [comment]
我最近重新看了一下相关的代码，我猜你之前的意思是如果我改变了caption和label的文件后，我需要清空cache，然后再重新跑DPR的test才能重新确定改变后检索到的文章，如果不重新跑DPR的test那么检索到的文章就不会因caption和label的改变而改变是吧？
