### ISSUE TITLE
Missing maskrcnn_benchamrk.data module

### ISSUE THREAD

**Issue by yao-jz** [LinWeizheDragon/Retrieval-Augmented-Visual-Question-Answering#2]
Thanks for your paper and shared codes!

When I tried to generate the VinVL object features, I run the following script:

```script
python tools/test_sg_net.py \
    --config-file sgg_configs/vgattr/vinvl_x152c4_okvqa_testset.yaml  \
    TEST.IMS_PER_BATCH 8  \
    MODEL.WEIGHT models/vinvl/vinvl_vg_x152c4.pth  \
    MODEL.ROI_HEADS.NMS_FILTER 1  \
    MODEL.ROI_HEADS.SCORE_THRESH 0.2  \
    DATA_DIR "./datasets/"  \
    TEST.IGNORE_BOX_REGRESSION True  \
    MODEL.ATTRIBUTE_ON True  \
    TEST.OUTPUT_FEATURE True
```

But it went into an error: 

```
Traceback (most recent call last):
  File "tools/test_sg_net.py", line 14, in <module>
    from maskrcnn_benchmark.data import make_data_loader
ModuleNotFoundError: No module named 'maskrcnn_benchmark.data'
```

When I checked the `materials/scene_graph_benchmark` folder, there wasn't a data module.

Could you tell me how to solve this problem? Thanks!

**Comment by yao-jz** [comment]
I used another scene_graph_benchmark repository's data module, and it helped.

**Comment by LinWeizheDragon** [comment]
Thanks for finding this bug. Actually, it is because the .gitignore file ignores all `data` folders.
I have added the missing files. You can pull and run again.

**Comment by yao-jz** [comment]
Thanks!
