### ISSUE TITLE
训练RAVQA时，评估阶段输出没有结果

### ISSUE THREAD

**Issue by 1286169349** [LinWeizheDragon/Retrieval-Augmented-Visual-Question-Answering#23]
下边是训练阶段给出的输出：
ace <--->     (<PAD> [SEP] <PAD> [SEP] <PAD> [SEP])
vine <--->     (<PAD> [SEP] <PAD> [SEP] <PAD> [SEP])
stuffed animal <--->     (<PAD> [SEP] <PAD> [SEP] <PAD> [SEP])
mouth <--->     (<PAD> [SEP] <PAD> [SEP] <PAD> [SEP])
下方是训练阶段时给出的评估结果：
{'test/accuracy_AnswerType_other': 0.04,
 'test/accuracy_QuestionType_eight': 0.0,
 'test/accuracy_QuestionType_five': 0.12,
 'test/accuracy_QuestionType_four': 0.0,
 'test/accuracy_QuestionType_nine': 0.0,
 'test/accuracy_QuestionType_one': 0.0,
 'test/accuracy_QuestionType_other': 0.19,
 'test/accuracy_QuestionType_seven': 0.0,
 'test/accuracy_QuestionType_six': 0.0,
 'test/accuracy_QuestionType_ten': 0.0,
 'test/accuracy_QuestionType_three': 0.0,
 'test/accuracy_QuestionType_two': 0.0,
 'test/accuracy_overall': 0.04,
 'test/epoch': 3,
 'test/exact_match_at_1': 0.0,
 'test/exact_match_at_2': 0.00019817677368212446,
 'test/exact_match_at_3': 0.00019817677368212446,
 'test/exact_match_at_4': 0.00019817677368212446,
 'test/exact_match_at_5': 0.00019817677368212446,
 'test/failed_hit': 0.0014665081252477209,
 'test/failed_no_hit': 0.9984542211652794,
 'test/gold_precision_at_5': 0.42663495838287757,
 'test/gold_recall_at_5': 0.7201743955608403,
 'test/n_retrieved_docs': 5,
 'test/precision_at_5': 0.5906856916369402,
 'test/recall_at_5': 0.8563218390804598,
 'test/selected_failed_hit': 0.0011890606420927466,
 'test/selected_failed_no_hit': 0.9988109393579072,
 'test/selected_successful_hit': 0.0,
 'test/selected_successful_no_hit': 0.0,
 'test/successful_hit': 3.963535473642489e-05,
 'test/successful_no_hit': 3.963535473642489e-05}

我发现是下边的代码可能有问题：好像是预测的结果被截断了。请问我需要修改代码吗？
rag_executor.py:
        bos_token_id = self.data_loader.decoder_tokenizer.bos_token_id  #bos_token_id =30531
        for index, i in enumerate(labels):
            cleaned_i = [label if label!=-100 else self.decoder_tokenizer.pad_token_id for label in i]
            cleaned_i = torch.LongTensor(cleaned_i)
            decoded_label = self.decoder_tokenizer.decode(cleaned_i, skip_special_tokens=True)  
            
            output_sequence = outputs[index]
            # print('output_sequence', output_sequence)
            cleaned_i = [label if label!=-100 else self.decoder_tokenizer.pad_token_id for label in output_sequence]
            cleaned_i = torch.LongTensor(cleaned_i)

            output_sequence = output_sequence.cpu().numpy().tolist()

            if bos_token_id in output_sequence:
                output_sequence = output_sequence[output_sequence.index(bos_token_id):]

            decoded_output = self.decoder_tokenizer.decode(output_sequence, skip_special_tokens=True)
            actual_output = self.decoder_tokenizer.decode(output_sequence, skip_special_tokens=False)
            # print(self.tokenizer.decode(cleaned_i, skip_special_tokens=True))
            
            if batch_idx < 10:
                print(decoded_label, '<--->', decoded_output, '   ({})'.format(actual_output))

**Comment by 1286169349** [comment]
请问有人遇到此问题吗？万分感谢

**Comment by LinWeizheDragon** [comment]
问过其他用过代码的学生，正确训练模型的话不会出现没有输出的情况
请先检查是否大范围改动过原来的代码，以及是否训练模型至少一个epoch
