### ISSUE TITLE
下载相关

### ISSUE THREAD

**Issue by Siri-2001** [LinWeizheDragon/Retrieval-Augmented-Visual-Question-Answering#25]
您好，您的工作很棒，我对您的工作十分感兴趣。但是我在下载46G的data.zip的时候遇到了问题，下载始终失败。请问您是否可以提供百度网盘的链接。十分感谢！

**Comment by LinWeizheDragon** [comment]
Hope this helps your research.

链接：https://pan.baidu.com/s/1hULW2dfFFngYggc9peZ4Uw?pwd=rmfv 
提取码：rmfv 
--来自百度网盘超级会员V9的分享

**Comment by Siri-2001** [comment]
收到，十分感谢！
