### ISSUE TITLE
下载相关https://biglmdiag.blob.core.windows.net/vinvl/datasets/coco_caption

### ISSUE THREAD

**Issue by cmcv2022** [LinWeizheDragon/Retrieval-Augmented-Visual-Question-Answering#27]
![3](https://github.com/LinWeizheDragon/Retrieval-Augmented-Visual-Question-Answering/assets/40625316/1cca254b-e308-4f27-83b1-3b17932b2211)
你好，这两个文件下载有问题，请问这两个问件能分享下吗，谢谢！

**Comment by LinWeizheDragon** [comment]
Please refer to my response to this issue.  
https://github.com/LinWeizheDragon/Retrieval-Augmented-Visual-Question-Answering/issues/16#issuecomment-1723073489

**Comment by EstrellaXyu** [comment]
> ![3](https://private-user-images.githubusercontent.com/40625316/291138058-1cca254b-e308-4f27-83b1-3b17932b2211.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY3NTYwODksIm5iZiI6MTczNjc1NTc4OSwicGF0aCI6Ii80MDYyNTMxNi8yOTExMzgwNTgtMWNjYTI1NGItZTMwOC00ZjI3LTgzYjEtM2IxNzkzMmIyMjExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEzVDA4MDk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzN2YzYzgzOTQ4MWE0ODNjOWM1ZTkyYWVkODA1Y2U0OTIwYjhiMGM1Njg2MmQxNGU4NmEzNWMzOTU5ZGMxOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zn0dir2gOf8av7DzE0ymzYg1iFG0oGfNOo1sdy8NDtQ) 你好，这两个文件下载有问题，请问这两个问件能分享下吗，谢谢！

Hello, we are also unable to download the .yaml file, have you successfully downloaded the file? can you please share it? Thanks a lot.
