### ISSUE TITLE
Release code of Fine-grained Late-interaction Multi-modal Retrieval (FLMR)

### ISSUE THREAD

**Issue by bianzheng123** [LinWeizheDragon/Retrieval-Augmented-Visual-Question-Answering#28]
Hello,
First of all, I want to express my gratitude for your interesting paper: Fine-grained Late-interaction Multi-modal Retrieval for Retrieval Augmented Visual Question Answering. 

After thoroughly reviewing your paper, I am eager to delve deeper into the methodologies and experiments you have presented. To this end, I am particularly interested in the code that underpins your research, as it would greatly aid in understanding and potentially replicating your groundbreaking work.

I understand the complexities and time constraints associated with preparing code for public release, yet I believe that access to the code would not only benefit me but also contribute significantly to the broader academic community. It would enable a more comprehensive understanding of your work and foster further research in the field.

Thank you for your consideration and for the remarkable contributions your research has made to the field. I look forward to the possibility of exploring your work more deeply and the release of the code.

**Comment by LinWeizheDragon** [comment]
Thank you for your interest. As mentioned in another issue, we are currently working on releasing the code. It is slow because we had another project to close up and we just finished our trip to New Orleans.
Currently, we plan to release the training/eval code before the end of Jan.

**Comment by gsxf997** [comment]
Hello, may I ask if you plan to release the code in the near future? I have encountered some issues while trying to replicate the results based on the paper.

> Thank you for your interest. As mentioned in another issue, we are currently working on releasing the code. It is slow because we had another project to close up and we just finished our trip to New Orleans. Currently, we plan to release the training/eval code before the end of Jan.

Hello, may I ask if you plan to release the code in the near future? I have encountered some issues while trying to replicate the results based on the paper.

**Comment by LinWeizheDragon** [comment]
> based

Hi,

I just finished code cleanup, and plan to release the code in the next 3 days. 

Best, 
Weizhe Lin

**Comment by LinWeizheDragon** [comment]
> Hello, may I ask if you plan to release the code in the near future? I have encountered some issues while trying to replicate the results based on the paper.
> 
> 
> 
> > Thank you for your interest. As mentioned in another issue, we are currently working on releasing the code. It is slow because we had another project to close up and we just finished our trip to New Orleans. Currently, we plan to release the training/eval code before the end of Jan.
> 
> 
> 
> Hello, may I ask if you plan to release the code in the near future? I have encountered some issues while trying to replicate the results based on the paper.

Hi,

I just finished code cleanup, and plan to release the code in the next 3 days.

Best,
Weizhe Lin

**Comment by gsxf997** [comment]
> > Hello, may I ask if you plan to release the code in the near future? I have encountered some issues while trying to replicate the results based on the paper.
> > > Thank you for your interest. As mentioned in another issue, we are currently working on releasing the code. It is slow because we had another project to close up and we just finished our trip to New Orleans. Currently, we plan to release the training/eval code before the end of Jan.
> > 
> > 
> > Hello, may I ask if you plan to release the code in the near future? I have encountered some issues while trying to replicate the results based on the paper.
> 
> Hi,
> 
> I just finished code cleanup, and plan to release the code in the next 3 days.
> 
> Best, Weizhe Lin

Thank you for your response, looking forward to it very much.

**Comment by LinWeizheDragon** [comment]
Hi all, 

The code for FLMR has been released. Other authors have verified the installation.

Best,
Weizhe Lin
