### ISSUE TITLE
FLMR中Feature-based Vison的一些问题

### ISSUE THREAD

**Issue by yjwang97** [LinWeizheDragon/Retrieval-Augmented-Visual-Question-Answering#29]
![屏幕截图 2024-01-04 111647](https://github.com/LinWeizheDragon/Retrieval-Augmented-Visual-Question-Answering/assets/139326482/1694ae9e-a831-4abb-b38a-34b0c813a13b)
您好，我最近在尝试根据论文复现FLMR的代码，我注意到在论文的表二中使用了Feature-based vision，这里的视觉特征是指通过Vit得到的整张图片的特征吗？这部分特征是否经过了与文本的对齐呢？

**Comment by yjwang97** [comment]
我注意到您是通过Vit来得到Feature-based Vision，那么这部分vision feature是否指识别到的object的特征呢？希望您能给我一些具体的细节。非常感谢！

**Comment by LinWeizheDragon** [comment]
你可以仔细读一下论文  这部分是用ViT提取的global的整张图的特征（因此是一个），没有与文本对齐，而是直接和text features并列
后面9ROI才加上九个bounding box用ViT提取的features
