### ISSUE TITLE
Missing file okvqa/train_okvqa.yaml and okvqa/test_okvqa.yaml 

### ISSUE THREAD

**Issue by yao-jz** [LinWeizheDragon/Retrieval-Augmented-Visual-Question-Answering#3]
Thanks for your paper and shared codes!

When I tried to generate the VinVL object features, I run the following script:

```script
python tools/test_sg_net.py \
    --config-file sgg_configs/vgattr/vinvl_x152c4_okvqa_testset.yaml  \
    TEST.IMS_PER_BATCH 8  \
    MODEL.WEIGHT models/vinvl/vinvl_vg_x152c4.pth  \
    MODEL.ROI_HEADS.NMS_FILTER 1  \
    MODEL.ROI_HEADS.SCORE_THRESH 0.2  \
    DATA_DIR "./datasets/"  \
    TEST.IGNORE_BOX_REGRESSION True  \
    MODEL.ATTRIBUTE_ON True  \
    TEST.OUTPUT_FEATURE True
```

But it didn't find the file `okvqa/train_okvqa.yaml` or `okvqa/test_okvqa.yaml`.

I checked the `vinvl_x152c4_okvqa_testset.yaml` file, and its DATASETS part's TRAIN and TEST dataset yaml file couldn't be found in the pre-processed data folder.

Could you tell me where to find those files or if I did something wrong?

Thanks!

**Comment by LinWeizheDragon** [comment]
It seems that we need to add some yaml files manually after creating the dataset. Working on this.

**Comment by LinWeizheDragon** [comment]
@yao-jz Hi, I have uploaded the configs files that need to be put together with the dataset files you created by running `prepare_data_for_okvqa/fvqa.py`. Could you try again?
Sorry for the inconvenience - the VinVL repository is too messy...

**Comment by yao-jz** [comment]
Thank you for the update.

I added those files, but it still had an error: can't find file `VG-SGG-dicts-vgoi6-clipped.json`.

Is the file `VG-SGG-dicts-danfeiX-clipped.json` here the same as the `VG-SGG-dicts-vgoi6-clipped.json`?

**Comment by LinWeizheDragon** [comment]
Hi, these files are from their repository. I think they have some tiny differences. Maybe you can check their repository for some explanations? I couldn't remember the details
I have uploaded the file you mentioned.

**Comment by yao-jz** [comment]
Thanks!
