### ISSUE TITLE
关于代码中TRiG中检索器的问题

### ISSUE THREAD

**Issue by zhaoyongchao2019** [LinWeizheDragon/Retrieval-Augmented-Visual-Question-Answering#30]
你好，我最近想在你代码中提供的TRiG框架中DPR检索器之上做一些改进，我希望能先得到DPR检索的topk100篇文章，然后再用自己的rerank模块重新排序然后把前五篇文章再放回TRiG中生成答案。所以我想问的是你可以给我一点提示，大概在哪部分的代码能得到关于每个问题检索的topk篇文章吗？

**Comment by LinWeizheDragon** [comment]
你好，训练完DPR以后跑DPR test可以得到top100的一个文件，你可以读取那个文件，然后在你自己的reranker中读取并且重新排序。将新的文件替换旧的文件之后就可以用rerank后的docs直接训练TRiG了

**Comment by zhaoyongchao2019** [comment]
非常非常感谢
