### ISSUE TITLE
Question about using BLIP2 as the answer generator

### ISSUE THREAD

**Issue by qwqwq1445** [LinWeizheDragon/Retrieval-Augmented-Visual-Question-Answering#34]
Thanks for your valuable work!
I am investigating RA-VQA and studying your previous work **Fine-grained Late-interaction Multi-modal Retrieval for Retrieval Augmented Visual Question Answering**. In this paper, you mention that you use BLIP2 as your answer generator. I wonder if you input the whole image into BLIP2 to generate answer?
Looking forward to your apply.

**Comment by LinWeizheDragon** [comment]
Yes. In answer generation, the whole image is input to BLIP2 as instructed by its documentation.
You can find relevant code in this repo.
