### ISSUE TITLE
Hello author, can I convert the weight format of this training to the format of hugging face, like FLMR

### ISSUE THREAD

**Issue by zzk2021** [LinWeizheDragon/Retrieval-Augmented-Visual-Question-Answering#43]

**Comment by LinWeizheDragon** [comment]
Could you please write in English so that the issue is accessible to a wider range of audience?

Which model do you want to convert? See https://github.com/LinWeizheDragon/FLMR/blob/main/tools/convert_flmr_original_checkpoint_to_pytorch.py for a script that converts lightning weights to hf.

**Comment by zzk2021** [comment]
> Could you please write in English so that the issue is accessible to a wider range of audience?
> 
> Which model do you want to convert? See https://github.com/LinWeizheDragon/FLMR/blob/main/tools/convert_flmr_original_checkpoint_to_pytorch.py for a script that converts lightning weights to hf.

thanks so much!
