### ISSUE TITLE
Retrieval from multi-modal document in appendix H

### ISSUE THREAD

**Issue by qinguangming1999** [LinWeizheDragon/Retrieval-Augmented-Visual-Question-Answering#45]
I'd like use your multi-modal retrieval version in appendix H as baseline, could you please provide the code and dataset WIT. Thanks a lot.

**Comment by LinWeizheDragon** [comment]
Hi, you can use the code in the FLMR repository (https://github.com/LinWeizheDragon/FLMR). It provides the codes to run the model, index multi-modal corpus, and fine-tune it on custom datasets, although you may need to modify the fine-tuning codes slightly to utilise multimodal documents in training.

Unfortunately, as this is a side experiment, I did not save the WIT corpus used in this part. 
You have three options:
1. use your own dataset
2. try to prepare a OKVQA dataset accompanied by a WIT corpus using similar approaches [here](https://github.com/LinWeizheDragon/Retrieval-Augmented-Visual-Question-Answering/issues/38#issuecomment-2088963720). The method in the thread uses official splits, as described in the paper.
3. If you just need a multi-modal document corpus and it doesn't have to be exactly the same as the one in the paper, you can use the WIT dataset shared in the [M2KR benchmark](https://huggingface.co/datasets/BByrneLab/multi_task_multi_modal_knowledge_retrieval_benchmark_M2KR) and process it with the method described in 2.
