### ISSUE TITLE
How to evaluate the VQA performance?

### ISSUE THREAD

**Issue by Code-kunkun** [LinWeizheDragon/Retrieval-Augmented-Visual-Question-Answering#47]
If I want to evaluate the performance of VQA, what code should I run?

**Comment by LinWeizheDragon** [comment]
For FLMR, check out [here](https://github.com/LinWeizheDragon/Retrieval-Augmented-Visual-Question-Answering?tab=readme-ov-file#blip2-with-flmr)
For PreFLMR, we didn't provide a script for evaluation on VQA datasets. You can use the huggingface implementation of PreFLMR [here](https://github.com/LinWeizheDragon/FLMR) and integrate PreFLMR into any of your own frameworks.

**Comment by Code-kunkun** [comment]
Thank you for your response. Additionally, I've noticed that the Infoseek train set has a size of 676,441. Could you specify which 100k data are used during the training process?

**Comment by LinWeizheDragon** [comment]
Hi, we randomly sampled 100k during training. As noted, these samples were automatically created and concentrate on a small number of entities. So random sampling should be just fine!

**Comment by Code-kunkun** [comment]
Thanks for your reply!
