### ISSUE TITLE
Some bug when processing img_key

### ISSUE THREAD

**Issue by yao-jz** [LinWeizheDragon/Retrieval-Augmented-Visual-Question-Answering#5]
When generating VinVL features, in file: `prepare_data_for_okvqa.py`

The`img_key` is `''`.

`img_key = img_p.split('.')[0].split('_')[-1]` should be `img_key = str(imgId).zfill(12)`

The same for `ocr.py`

**Comment by LinWeizheDragon** [comment]
Thanks for pointing this out. I may forgot to update some of the codes. Just do whatever it works ^_^
