### ISSUE TITLE
The hardware requirements for this model.

### ISSUE THREAD

**Issue by zhaoyongchao2019** [LinWeizheDragon/Retrieval-Augmented-Visual-Question-Answering#8]
My two NVIDIA TITAN X GPUs with 12GB memory each can't handle this model. I'm wondering what hardware configuration others are using to run this model successfully.

**Comment by LinWeizheDragon** [comment]
12GB is quite small for T5-large models.
The hardware configuration I used:
A100 (80G) batch size 2 or 4, with T5-large and K=5
You may want to use batch size 1, with other smaller version of T5 and reduce K

The code implementation loads both the DPR-query-encoder and the T5-answer-generator. And K=5 documents were concatenated with the query and passed through the whole system. If you really want to run this model on a small GPU, you may try to pre-extract DPR predictions for each of the question beforehand, and load only the T5-answer-generator in training.

**Comment by LinWeizheDragon** [comment]
Btw, you can't even train T5-large with batch size 1 on 12GB GPU RAM with full precision.

**Comment by zhaoyongchao2019** [comment]
Thank you very much for your response. I would like to know if I can replace T5-large with a smaller model, and if other settings can remain unchanged?

**Comment by yao-jz** [comment]
You can replace T5-large with T5-base/T5-small, and set K = 3 (or smaller).

**Comment by zhaoyongchao2019** [comment]
Thank you all for your kind help. I have now switched to T5-small and managed to run the model successfully. Thank you, everyone.

**Comment by LinWeizheDragon** [comment]
Thanks for helping answering the question @yao-jz !
Just one note: t5-small and t5-base may have a shorter input length limit. In that case, you should also change `model_config.decoder_input_length=512` to a proper value (in order to avoid some bugs)
